### ISSUE TITLE
English support

### ISSUE THREAD

**Issue by matrunchyk** [likaia/vue-native-websocket-vue3#1]
Hello, thanks for a good package!

Just wondering about any possibility to have descriptions on GitHub and comments on the source code in English language?

**Comment by likaia** [comment]
No problem, but it will take a few days for me to submit it. I have other things to do these days.😉
Can I leave a contact information and add you as a friend😄, Facebook? WeChat? Twitter? ins? Or other.

**Comment by matrunchyk** [comment]
Sure! Do you have Telegram? Mine is https://t.me/matrunchyk.

**Comment by likaia** [comment]
Okay, I applied to be your friend

**Comment by likaia** [comment]
Translation work is complete😁
