### ISSUE TITLE
New release with latest commit

### ISSUE THREAD

**Issue by maddie** [likaia/vue-native-websocket-vue3#11]
Is it possible to release a new version with the latest Vite fix?

Thanks!!

**Comment by likaia** [comment]
ok，现在弄

**Comment by likaia** [comment]
新版本已推送至npm，版本号为：3.1.3

**Comment by maddie** [comment]
![image](https://user-images.githubusercontent.com/221872/126869763-0993a65e-21f9-471d-815f-5ea74564bf10.png)

3.1.3下载下来import里面的路径还是原来的诶

**Comment by likaia** [comment]
😂忘记打包了，稍等

**Comment by likaia** [comment]
见鬼，我打包报错了😂，你试试看看能打包插件不。
![image](https://user-images.githubusercontent.com/35120858/126871322-32cba6c3-2195-4c5a-8e1e-50117f0322bb.png)

**Comment by maddie** [comment]
我`yarn install`的时候node-gyp编译失败😂

**Comment by likaia** [comment]
啊 这😂  你换个源试试

**Comment by maddie** [comment]
不知道是不是Xcode的问题，一直build不了

**Comment by likaia** [comment]
我找了5个网友都试了下build，他们也都build不了

**Comment by likaia** [comment]
搞定了，插件版本更新到3.1.4就看到了。

**Comment by maddie** [comment]
可以了！！

感谢！
