### ISSUE TITLE
Migrating from vue-native-websocket-vue  with vuex

### ISSUE THREAD

**Issue by vricosti** [likaia/vue-native-websocket-vue3#12]
Hi,

I am migrating my project from Vue2 and I was using vue-native-websocket-vue with vuex.
To send some websocket message I was using the syntax Vue.prototype.$socket.sendObj: 

./store/store.js
```
SEND_MESSAGE: (state, message) => {
      if (state.socket.isConnected) {
        Vue.prototype.$socket.sendObj(message);
      } else {
        const intervalId = setInterval(() => {
          if (state.socket.isConnected) {
            Vue.prototype.$socket.sendObj(message);
            clearInterval(intervalId);
          }
        }, 1000);
      }
    },
```
Inside main.js I am using the code:

```
import App from "@/App.vue";

import {
  SOCKET_ONOPEN,
  SOCKET_ONCLOSE,
  SOCKET_ONERROR,
  SOCKET_ONMESSAGE,
  SOCKET_RECONNECT,
  SOCKET_RECONNECT_ERROR
} from "@/store/mutations-ws-types";

const mutations = {
  SOCKET_ONOPEN,
  SOCKET_ONCLOSE,
  SOCKET_ONERROR,
  SOCKET_ONMESSAGE,
  SOCKET_RECONNECT,
  SOCKET_RECONNECT_ERROR
};

const app = createApp(App);
app.use(store)
app.use(router)
app.use(VueNativeSock, "ws://127.0.0.1:9004", {
  store: store,
  mutations: mutations,
  format: "json",
  reconnection: true, // (Boolean) whether to reconnect automatically (false)
  // reconnectionAttempts: 5, // (Number) number of reconnection attempts before giving up (Infinity),
  reconnectionDelay: 1000 // (Number) how long to initially wait before attempting a new (1000)
});
app.use(vfmPlugin)
app.component('VueToggles', VueToggles);
app.component('font-awesome-icon', FontAwesomeIcon)
app.mount('#app')
```

So how should I replace Vue.prototype.$socket.sendObj ?

**Comment by likaia** [comment]
You can use `this.$socket.sendObj({msg: 'text content'});` to sendMessage.

It is written in the document, I hope you can read the document.

**Comment by likaia** [comment]
If you want to use in the store, need import main.js.

![image](https://user-images.githubusercontent.com/35120858/128018865-615c5c80-e3ec-4747-95ee-d7ff0de6449e.png)

**Comment by vricosti** [comment]
yeah actually I am trying but with no success, I am replacing main with app.
(sidenote: I am finally using typescript only inside main.ts instead of main.js because as soon as I have added typescript package for one of  an external component vue was looking for it.)




```
import app from "@/main";

mutations: {
    [SOCKET_ONOPEN](state, event ) {
      app.config.globalProperties.$socket = event.currentTarget;
      state.socket.isConnected = true;
    },
```
and I get:

Uncaught TypeError: Cannot read property 'globalProperties' of undefined
    at Store.<anonymous> (store.js:201)

**Comment by likaia** [comment]
你可以参考下我项目里的用法，按着我的来，应该是没问题的。[main.ts#L25](https://github.com/likaia/chat-system/blob/ac4c0ba0af54bab96890ef5c50017f3e35a35051/src/main.ts#L25)

**Comment by vricosti** [comment]
thanks
