### ISSUE TITLE
文档错误指正

### ISSUE THREAD

**Issue by sdtime-io** [likaia/vue-native-websocket-vue3#15]
https://github.com/likaia/vue-native-websocket-vue3#%E5%90%AF%E7%94%A8vuex%E9%9B%86%E6%88%90
这里启用 vuex 中，调用了  `main.config.globalProperties.$socket.sendObj(...)` 函数，实际使用中，sendObj函数 undefined， 应该调用 send 函数

**Comment by likaia** [comment]
文档没错，sendObj方法，需要启用JSON消息传递时才能用。我在文档中更正了。

> 注意：`sendObj`方法必须在你启用JSON消息传递时才可以使用，不然只能使用`send`方法。
