### ISSUE TITLE
Cannot read properties of undefined (reading '$socket')

### ISSUE THREAD

**Issue by mengxin-FE** [likaia/vue-native-websocket-vue3#18]
在vue3组合式API中开发，this是undefined的，因而不能使用 this.$socket...... 请问该如何调用$socket.send
<script setup name="socket">
    const msg = '发送测试数据'
    function sendMsg () {
        // 调用send方法，以字符串形式发送数据
        this.$socket.send(msg);
    }
</script>

项目文档描述：
在组件中使用
做完上述配置后，就可以在组件中使用了，如下所示为发送数据的例子。
export default defineComponent({
  methods: {
    clickButton: function(val) {
        // 调用send方法，以字符串形式发送数据
        this.$socket.send('some data');
        // 如果fomat配置为了json，即可调用sendObj方法来发送数据
        this.$socket.sendObj({ awesome: 'data'} );
    }
  }
})

**Comment by likaia** [comment]
看文档，文档有写

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/35120858/168240311-9b1c2f0b-510e-4ebf-8731-28a27b239b4c.png">
