### ISSUE TITLE
Could you help to provide a guide with quasar ui framework?

### ISSUE THREAD

**Issue by skaihahaha** [likaia/vue-native-websocket-vue3#19]
Could you help to provide a guide with quasar ui framework?

as the main.js/main.ts is not presented in the quasar project. It is difficult for me to construct a project with vue-native-websocket-vue3, quasar, pinia.

Thanks.

**Comment by likaia** [comment]
The documentation describes how to configure pinia, you may need to learn how to use pinia first.

**Comment by likaia** [comment]
> Could you help to provide a guide with quasar ui framework?
> 
> as the main.js/main.ts is not presented in the quasar project. It is difficult for me to construct a project with vue-native-websocket-vue3, quasar, pinia.
> 
> Thanks.

The pinia demo is written, please move: [pinia-websocket-project](https://github.com/likaia/pinia-websocket-project)
