### ISSUE TITLE
Accessing $socket in Vue2

### ISSUE THREAD

**Issue by HtheChemist** [likaia/vue-native-websocket-vue3#2]
In the Vue2 version you can access $socket using:
Vue.prototype.$socket

However in this version you use
main.config.globalProperties.$socket

My current Vue2 setup does not export 'main' so is there a way to access it through prototype?

**Comment by likaia** [comment]
My plugin is not backward compatible, please move to [vue-native-websocket](https://github.com/nathantsoi/vue-native-websocket) for vue2 version
