### ISSUE TITLE
Help: I don't know how to use it with Pinia

### ISSUE THREAD

**Issue by leoNavarro95** [likaia/vue-native-websocket-vue3#20]
Please can you supply an example where Pinia it is used. I'm trying with the documentation provided but I don't get it yet. 

I will apreciate any help

**Comment by likaia** [comment]
I'm not very familiar with Pinia. I've been busy recently, and I don't have time to write a demo for you. I'll write it for you in a while.

**Comment by leoNavarro95** [comment]
I think I managed to make it work, but I have doubts, mainly with the structure of the configuration files.

Anyways I think It is really important to provide at least a more detailed code example, maybe I am the only one who don´t get it, and it is my fault :(

A really appreciate your time.
Greetings

**Comment by likaia** [comment]
> I think I managed to make it work, but I have doubts, mainly with the structure of the configuration files.
> 
> Anyways I think It is really important to provide at least a more detailed code example, maybe I am the only one who don´t get it, and it is my fault :(
> 
> A really appreciate your time. Greetings

It's okay, I'll write a demo on Saturday

**Comment by likaia** [comment]
> > I think I managed to make it work, but I have doubts, mainly with the structure of the configuration files.
> > Anyways I think It is really important to provide at least a more detailed code example, maybe I am the only one who don´t get it, and it is my fault :(
> > A really appreciate your time. Greetings
> 
> It's okay, I'll write a demo on Saturday

The demo is written, please move: [pinia-websocket-project](https://github.com/likaia/pinia-websocket-project)

**Comment by likaia** [comment]
> I think I managed to make it work, but I have doubts, mainly with the structure of the configuration files.
> 
> Anyways I think It is really important to provide at least a more detailed code example, maybe I am the only one who don´t get it, and it is my fault :(
> 
> A really appreciate your time. Greetings

The demo is written, please move: [pinia-websocket-project](https://github.com/likaia/pinia-websocket-project)

Can you leave one of your Telegram? i want to be friends with you.

**Comment by leoNavarro95** [comment]
Hi! Thank you very much, I will review the demo.
My Telegram user is @LeoNavarro95

**Comment by leoNavarro95** [comment]
Sorry, I have changed the user it is this one 
https://t.me/LeoAutomation

**Comment by likaia** [comment]
> Sorry, I have changed the user it is this one https://t.me/LeoAutomation

OK
