### ISSUE TITLE
启用手动链接，proxy.$connect is not function

### ISSUE THREAD

**Issue by yin2017168** [likaia/vue-native-websocket-vue3#23]
app.use(
    VueNativeSock,
    '',
    {
        // 启用pinia集成 | enable pinia integration
        store: piniaSocketStore,
        // 数据发送/接收使用使用json
        format: 'json',
        // 开启手动调用 connect() 连接服务器
        connectManually: true,
        // 开启自动重连
        reconnection: true,
        // 尝试重连的次数
        reconnectionAttempts: 5,
        // 重连间隔时间
        reconnectionDelay: 3000
    }
)

**Comment by likaia** [comment]
这个应该只是你的ide报错吧，你可以从appContext.config.globalProperties中拿proxy

**Comment by yin2017168** [comment]
时启动项目后，程序报错！
