### ISSUE TITLE
HMR热更新失败

### ISSUE THREAD

**Issue by geekzsp** [likaia/vue-native-websocket-vue3#28]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/23443948/213079483-058892c7-3e2e-4490-bdc5-805103b72a52.png">

<img width="540" alt="image" src="https://user-images.githubusercontent.com/23443948/213079533-be00f446-dacf-444f-a6cf-652e4fce1a54.png">
看起来 useSocketStore.ts 引入main 导致的热更新失败？不知道咋改

**Comment by likaia** [comment]
你用的是pinia吗？

**Comment by geekzsp** [comment]
是的，pinia +vite

**Comment by likaia** [comment]
> 是的，pinia +vite

那你有试过我这个示例项目吗？看看会不会失败

https://github.com/likaia/pinia-websocket-project

**Comment by geekzsp** [comment]
> > 是的，pinia +vite
> 
> 那你有试过我这个示例项目吗？看看会不会失败
> 
> https://github.com/likaia/pinia-websocket-project

试过了，这个项目是可以正常热部署的，所以目前怀疑是vite配置问题

**Comment by likaia** [comment]
> > > 是的，pinia +vite
> > 
> > 
> > 那你有试过我这个示例项目吗？看看会不会失败
> > https://github.com/likaia/pinia-websocket-project
> 
> 试过了，这个项目是可以正常热部署的，所以目前怀疑是vite配置问题

那我就也不知了，不是插件导致的就行。

good luck.
