### ISSUE TITLE
可以配置header吗，因为我想将token放在里面做验证

### ISSUE THREAD

**Issue by mark342703702** [likaia/vue-native-websocket-vue3#29]
可以配置header吗，因为我想将token放在里面做验证

**Comment by likaia** [comment]
暂时不能，我看下能不能加上去

**Comment by likaia** [comment]
> 可以配置header吗，因为我想将token放在里面做验证

我查了下资料，这个是做不到的。websocket连接在前端是没办法自定义http header的，如果一定要往header里塞东西那就在nginx那边做一下处理。具体可以看这篇文章：https://blog.csdn.net/wanggmm/article/details/128631501
