### ISSUE TITLE
有没有pub/sub的例子 （examples for connect and subscribe paradigm)

### ISSUE THREAD

**Issue by uniquejava** [likaia/vue-native-websocket-vue3#3]
我了解的spring boot + vue大部分例子都是用stomp over sockjs
stomp.connect("....", callback) 然后在callback中可以 subscribe不同的topic/channel， 如果用这个vue-native-websocket-vue3插件改怎么做。

**Comment by likaia** [comment]
socketJs我不太懂，他和websocket协议应该不同吧，你如果使用我这个插件的话，前端部分按照README.md文档来就行，后端接口实现的话，你得根据websocket的协议进行相关实现。

我的后端用的是 javax.websocket.*实现的

**Comment by uniquejava** [comment]
got it。 因为手机端不支持sockjs， 所以我把sockjs去掉拉！

我们的web端是vue3 (script setup)， 手机端是 iOS swift,   后端是spring boot + spring websocket/messaging,  我最终选了纯typescript编写的库[stompjs](https://github.com/stomp-js/stompjs),     
和spring websocket搭配很👌。 支持掉线重连， 也支持pub/sub消息模型。

文档： https://stomp-js.github.io/guide/stompjs/using-stompjs-v5.html
