### ISSUE TITLE
Can not to import

### ISSUE THREAD

**Issue by hamedg68** [likaia/vue-native-websocket-vue3#30]
I am using **vite** and in **main.ts** file I have this error

**Could not find a declaration file for module 'vue-native-websocket-vue3'. '..../node_modules/vue-native-websocket-vue3/dist/vueNativeWebsocket.common.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vue-native-websocket-vue3` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-native-websocket-vue3**
  
According to error message I try to install **@types/vue-native-websocket-vue3** but I have the following error

**error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2fvue-native-websocket-vue3: Not found".**

**Comment by likaia** [comment]
I have a project that is also built based on vite+vue3+ts, and it can run normally. You can refer to the writing method of my project to troubleshoot the problem.

[chat-system](https://github.com/likaia/chat-system)

**Comment by hamedg68** [comment]
Ok! I have cloned the **chat-system** however the project runs but in **main.ts** I have the same **typescript** **error**

**Comment by likaia** [comment]
> Ok! I have cloned the **chat-system** however the project runs but in **main.ts** I have the same **typescript** **error**

This is impossible, what editor are you using?

**Comment by hamedg68** [comment]
I am using **_vs-code_** editor

**Comment by likaia** [comment]
I tried vscode, it is normal and no error is reported.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/35120858/235551994-79cfa0b1-50cc-4a36-9f1c-e5594c8ae97b.png">

The project can also start normally.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/35120858/235552101-f0198ebe-a14f-4584-a8dc-407ea51f7d1e.png">

**Comment by xiaoji106** [comment]
Hi @likaia,

The error is caused by inconsistent capitalization of the first letter of the type file name.
In Linux, file names are strictly case-sensitive, so the error will not appear in Windows.

![image](https://github.com/user-attachments/assets/953fc1d5-7587-4c53-9381-c3bc867c8bd5)
![image](https://github.com/user-attachments/assets/4e249d32-8016-46e3-9f84-5b752e455ad2)

**Comment by likaia** [comment]
> Hi @likaia,
> 
> The error is caused by inconsistent capitalization of the first letter of the type file name. In Linux, file names are strictly case-sensitive, so the error will not appear in Windows.
> 
> ![image](https://private-user-images.githubusercontent.com/21170951/379165864-953fc1d5-7587-4c53-9381-c3bc867c8bd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzE2NjcsIm5iZiI6MTcyOTY3MTM2NywicGF0aCI6Ii8yMTE3MDk1MS8zNzkxNjU4NjQtOTUzZmMxZDUtNzU4Ny00YzUzLTkzODEtYzNiYzg2N2M4YmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA4MTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYTJiNzM5OGJlNWZlNmQxZjNjNGZlOTRhMWY0Y2YzNDQzMDJhZTRlY2VhZjAzMDY3MWU4NDUyMGM4NzZjMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NocbGy60QbgCJX1yrUirwFu9z2zeO6hBNt_eG-aeBjw) ![image](https://private-user-images.githubusercontent.com/21170951/379166068-4e249d32-8016-46e3-9f84-5b752e455ad2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzE2NjcsIm5iZiI6MTcyOTY3MTM2NywicGF0aCI6Ii8yMTE3MDk1MS8zNzkxNjYwNjgtNGUyNDlkMzItODAxNi00NmUzLTlmODQtNWI3NTJlNDU1YWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA4MTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYzU5ZjM2OWM4YTgyNDZjM2Q2NmZlYjk2YWIzOTY5NDBmMTRlYzRkZjRlODc3OTY3ZjhiYTJkZTZlYWMzNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6_cA-yE3E3dpBEY_kPwbIhEN5GJMspBMdPRgpPitars)

Got it. I'll change it.

**Comment by likaia** [comment]
> > Hi @likaia,
> > The error is caused by inconsistent capitalization of the first letter of the type file name. In Linux, file names are strictly case-sensitive, so the error will not appear in Windows.
> > ![image](https://private-user-images.githubusercontent.com/21170951/379165864-953fc1d5-7587-4c53-9381-c3bc867c8bd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzE2NjcsIm5iZiI6MTcyOTY3MTM2NywicGF0aCI6Ii8yMTE3MDk1MS8zNzkxNjU4NjQtOTUzZmMxZDUtNzU4Ny00YzUzLTkzODEtYzNiYzg2N2M4YmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA4MTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYTJiNzM5OGJlNWZlNmQxZjNjNGZlOTRhMWY0Y2YzNDQzMDJhZTRlY2VhZjAzMDY3MWU4NDUyMGM4NzZjMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NocbGy60QbgCJX1yrUirwFu9z2zeO6hBNt_eG-aeBjw) ![image](https://private-user-images.githubusercontent.com/21170951/379166068-4e249d32-8016-46e3-9f84-5b752e455ad2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzE2NjcsIm5iZiI6MTcyOTY3MTM2NywicGF0aCI6Ii8yMTE3MDk1MS8zNzkxNjYwNjgtNGUyNDlkMzItODAxNi00NmUzLTlmODQtNWI3NTJlNDU1YWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA4MTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYzU5ZjM2OWM4YTgyNDZjM2Q2NmZlYjk2YWIzOTY5NDBmMTRlYzRkZjRlODc3OTY3ZjhiYTJkZTZlYWMzNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6_cA-yE3E3dpBEY_kPwbIhEN5GJMspBMdPRgpPitars)
> 
> Got it. I'll change it.

Fixed, just update the version to 3.1.8
