### ISSUE TITLE
proxy.$connect() 编辑器报红，怎么解决

### ISSUE THREAD

**Issue by miaozhenkun** [likaia/vue-native-websocket-vue3#32]
proxy.$connect() 编辑器报红，怎么解决，感谢作者分享🙏

**Comment by likaia** [comment]
> proxy.$connect() 编辑器报红，怎么解决，感谢作者分享🙏

应该是我写的有问题，目前还没时间处理，我晚点修复下

**Comment by JiaLeD** [comment]
sos，我也出现了这个问题，希望作者能尽快解决，感谢

**Comment by likaia** [comment]
> sos，我也出现了这个问题，希望作者能尽快解决，感谢



> proxy.$connect() 编辑器报红，怎么解决，感谢作者分享🙏

我看了下，需要在项目中自己做处理。可以参考下我的处理方式：
* https://github.com/likaia/chat-system/blob/c9865ad3036a08799f026ac26dc1120d2f765ec0/src/type/global/UseCurrentInstance.ts#L1
* https://github.com/likaia/chat-system/blob/08f5e8590e75ca12644a8f550a13f228dbcf0b6f/src/components/main-content.vue#L196
* https://github.com/likaia/chat-system/blob/08f5e8590e75ca12644a8f550a13f228dbcf0b6f/src/components/main-content.vue#L207

**Comment by likaia** [comment]
> > sos，我也出现了这个问题，希望作者能尽快解决，感谢
> 
> > proxy.$connect() 编辑器报红，怎么解决，感谢作者分享🙏
> 
> 我看了下，需要在项目中自己做处理。可以参考下我的处理方式：
> 
> * https://github.com/likaia/chat-system/blob/c9865ad3036a08799f026ac26dc1120d2f765ec0/src/type/global/UseCurrentInstance.ts#L1
> * https://github.com/likaia/chat-system/blob/08f5e8590e75ca12644a8f550a13f228dbcf0b6f/src/components/main-content.vue#L196
> * https://github.com/likaia/chat-system/blob/08f5e8590e75ca12644a8f550a13f228dbcf0b6f/src/components/main-content.vue#L207

有关这个知识点的文章解析，请移步：
* https://www.kaisir.cn/post/92#%E8%AE%BF%E9%97%AE%E5%BD%93%E5%89%8D%E5%AE%9E%E4%BE%8B
