### ISSUE TITLE
 Could not find a declaration file for module 'vue-native-websocket-vue3'

### ISSUE THREAD

**Issue by Bin43** [likaia/vue-native-websocket-vue3#36]
我是TS新手，遇到一个棘手的问题，使用实例[pinia-websocket-project](https://github.com/likaia/pinia-websocket-project)运行没有任何问题，但执行build编译就报错，报错内容见下图
![QQ_1729233400370](https://github.com/user-attachments/assets/361c2e78-3cdd-4c56-b455-6752744b9242)

**Comment by likaia** [comment]
更新到3.1.8试试

**Comment by Bin43** [comment]
确实能解决我问题了，感谢🙏
