### ISSUE TITLE
Property '$socket' does not exist

### ISSUE THREAD

**Issue by DblK** [likaia/vue-native-websocket-vue3#4]
I can not use this library at all. `$socket` does not exist. Any help will be great.
I use Vue3 in Typescript.

`main.ts`:
```ts
import VueNativeSock from 'vue-native-websocket-vue3';
...
createApp(App)
  .use(VueNativeSock, 'ws://localhost:8080')
  .use(store)
  .use(router)
  .mount('#app');
```

In my component `Example.ts`:
```ts
export default class Example extends Vue {
  mounted() {
    this.$socket.send({event: 'events', data:'test' });

    // This works
    this.$options.sockets.onmessage = (res: {}) => {
      console.log(res);
    };
  }
}
```

Thank you for your help!

**Comment by bitcoinvsalts** [comment]
```this.$socket``` does not work for me neither, and

```this.$options.sockets.onmessage = (res) => {}```

is giving me:

```TypeError: Cannot read property '$options' of undefined```

**Comment by likaia** [comment]
Class component writing, I have not tried。I'm in optionsAPI and CompositionAPI Use is normal。
You can look at my code and compare it.

https://github.com/likaia/chat-system/blob/db35173c8e54834a117ac8cb5a3753e75d9b1161/src/module/message-display/main-entrance/EventMonitoring.ts#L50

https://github.com/likaia/chat-system/blob/db35173c8e54834a117ac8cb5a3753e75d9b1161/src/module/message-display/components-metords/SendMessage.ts#L73

https://github.com/likaia/chat-system/blob/91fe072a20d0928ff2af6c1bf56cedd0e545d0d5/src/views/contact-list.vue#L620

**Comment by bitcoinvsalts** [comment]
Thank you for this repo and your reply. I will take a look at it.

**Comment by DblK** [comment]
Did not get a chance yet to watch your example, I will take a look. Thanks

**Comment by ovidiuc** [comment]
I had the same problem, using Composition API. ~~It stopped working sometime around a Vue update I couldn't pinpoint. I was able to find it here:~~ I was using it in the wrong way, turns out. The below works:

```
import { getCurrentInstance } from 'vue';
export default {
    setup() {
        const app = getCurrentInstance();
        const socket = app.proxy.$socket;

    }
};
```
~~But I'm not sure that it is the proper way to access a plugin. It doesn't look like it, given the existing examples online.~~

**Comment by likaia** [comment]
No instance can be obtained in setup, You can refer to my writing.

https://github.com/likaia/chat-system/blob/a5ce2e9133c0d05f0d3f4249aae082edc435ac85/src/module/message-display/main-entrance/EventMonitoring.ts#L49

**Comment by ovidiuc** [comment]
Yes, that's how I had it, but it stopped working, `$socket` is no longer there for me. Maybe some Vue update. Or Quasar update, as I'm using Quasar Framework on top of Vue. Also note that I'm not using TS (which I think shouldn't matter here).

**Comment by likaia** [comment]
vue3 does not support this.

**Comment by ovidiuc** [comment]
I'm not using `this`, but either way, I was wrong, the `$socket` object is in `app.proxy`, as in your example. Not sure why it wasn't working for me the first time around, but it looks like an error on my behalf. I've edited my original post. Thanks for your help.

**Comment by likaia** [comment]
The vue document writes that `getCurrentInstance` can only be obtained in the `onMounted()` stage

**Comment by likaia** [comment]
On this issue, you can read my article. 

https://juejin.cn/post/6917592199140458504#heading-22
